# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"E\n\x04user\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"!\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"+\n\x0fGetUserResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.user\"\"\n\x11SearchUserRequest\x12\r\n\x05query\x18\x01 \x01(\t\"/\n\x12SearchUserResponse\x12\x19\n\x05users\x18\x01 \x03(\x0b\x32\n.user.user2\x86\x01\n\x0bUserService\x12\x36\n\x07GetUser\x12\x14.user.GetUserRequest\x1a\x15.user.GetUserResponse\x12?\n\nSearchUser\x12\x17.user.SearchUserRequest\x1a\x18.user.SearchUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USER']._serialized_start=20
  _globals['_USER']._serialized_end=89
  _globals['_GETUSERREQUEST']._serialized_start=91
  _globals['_GETUSERREQUEST']._serialized_end=124
  _globals['_GETUSERRESPONSE']._serialized_start=126
  _globals['_GETUSERRESPONSE']._serialized_end=169
  _globals['_SEARCHUSERREQUEST']._serialized_start=171
  _globals['_SEARCHUSERREQUEST']._serialized_end=205
  _globals['_SEARCHUSERRESPONSE']._serialized_start=207
  _globals['_SEARCHUSERRESPONSE']._serialized_end=254
  _globals['_USERSERVICE']._serialized_start=257
  _globals['_USERSERVICE']._serialized_end=391
# @@protoc_insertion_point(module_scope)
